config/routes.rb
Gestor::Application.routes.draw do
  resources :evaluable_competencies

  resources :teaching_units

  resources :evaluation_criteria

  resources :learning_outcomes

  resources :subject_competencies

  resources :level_goals

  resources :qualifications

  resources :competencies

  resources :level_descriptions

  resources :subjects

  resources :training_levels
  root :to => 'training_levels#index'
end

app/models/training_level.rb
require 'uri_validator'

class TrainingLevel < ActiveRecord::Base
  include ActsAsTree

  has_many :subjects, :dependent => :destroy
  has_one  :level_description
  has_many :competencies, :through => :level_description
  has_many :qualifications, :through => :level_description
  has_many :level_goals, :through => :level_description

  attr_accessible :description, :name, :short_name, :parent_id, :logo, :url
  acts_as_tree :order => "name"

  has_attached_file :logo, :styles => { :medium => "300x300>", 
                                        :small => "100x100>", 
                                        :tiny => "32x32>", 
                                        :invisible => "16x16>" },
                           :default_url => '/images/:attachment/missing_:style.png'
                                 
  before_create { |tl| tl.build_level_description }

  validates_uniqueness_of :name
  validates_uniqueness_of :short_name, :allow_blank => true
  validates_presence_of :name
  validates :url, :uri => { 
     :format => /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix }

     scope :roots, where(:parent_id => nil)

     def self.leaves
       tl = arel_table
       where(tl[:id].in( 
		select(:parent_id).uniq.map(&:parent_id).compact).not
	     )
     end
      

     class << self
       alias_method :modules, :leaves
     end

    def is_leaf?
       self.class.leaves.include? self
    end

end

app/controllers/training_levels_controller.rb
class TrainingLevelsController < ApplicationController
  # GET /training_levels
  # GET /training_levels.json
  def index
    @training_levels = TrainingLevel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @training_levels }
    end
  end

  # GET /training_levels/1
  # GET /training_levels/1.json
  def show
    @training_level = TrainingLevel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @training_level }
    end
  end

  # GET /training_levels/new
  # GET /training_levels/new.json
  def new
    @training_level = TrainingLevel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @training_level }
    end
  end

  # GET /training_levels/1/edit
  def edit
    @training_level = TrainingLevel.find(params[:id])
  end

  # POST /training_levels
  # POST /training_levels.json
  def create
    @training_level = TrainingLevel.new(params[:training_level])

    respond_to do |format|
      if @training_level.save
        format.html { redirect_to @training_level,  :notice => t('successfully_created', :model => t('training_level.gender', :count => 1) ) }
        format.json { render json: @training_level, status: :created, location: @training_level }
      else
        format.html { render action: "new" }
        format.json { render json: @training_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /training_levels/1
  # PUT /training_levels/1.json
  def update
    @training_level = TrainingLevel.find(params[:id])

    respond_to do |format|
      if @training_level.update_attributes(params[:training_level])
        format.html { redirect_to @training_level, :notice => t('successfully_updated', :model => t('training_level.gender', :count => 1) ) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @training_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /training_levels/1
  # DELETE /training_levels/1.json
  def destroy
    @training_level = TrainingLevel.find(params[:id])
    @training_level.destroy

    respond_to do |format|
      format.html { redirect_to training_levels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/training_levels_helper.rb
module TrainingLevelsHelper

end

app/views/training_levels/_form.html.erb
<%= form_for(@training_level, :html => { :multipart => true } ) do |f| %>

<%= error_explanation_for @training_level %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :short_name %><br />
    <%= f.text_field :short_name%>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url%>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.file_field :logo %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.collection_select :parent_id, TrainingLevel.all(:order => "name"), :id, :name, :include_blank => true %>
  </div>

  <p><%= render :partial => "level_descriptions/description_levers" if @training_level.is_leaf? %></p>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/training_levels/edit.html.erb
<h1><%= t('training_level.edit') %></h1>

<%= render 'form' %>

<%= link_to t('show'), @training_level %> |
<%= link_to t('back'), training_levels_path %>

app/views/training_levels/index.html.erb
<h1><%= t('training_level.list') %></h1>

<table>
  <tr>
    <th></th>
    <th><%= t('activerecord.attributes.training_level.name').capitalize %></th>
    <th><%= t('activerecord.attributes.training_level.parent').capitalize %></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @training_levels.each do |training_level| %>
  <tr>
    <td><%= conditional_link(training_level, image_tag(training_level.logo.url(:tiny))) %></td>
    <td><%= conditional_link(training_level, training_level.name) %> <%= "(#{training_level.short_name})" unless training_level.short_name.blank? -%></td>
    <td><%= training_level.parent.name if training_level.parent %></td>
    <td><%= link_to t('show'), training_level %></td>
    <td><%= link_to t('edit'), edit_training_level_path(training_level) %></td>
    <td><%= link_to t('destroy'), training_level, :confirm => t('are_you_sure'), :method => :delete %></td>
    <td><%= link_to t('subjects'), subjects_path(:scope => training_level) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('training_level.new').capitalize, new_training_level_path %>

app/views/training_levels/new.html.erb
<h1><%= t('training_level.new') -%></h1>

<%= render 'form' %>

<%= link_to t('back'), training_levels_path %>

app/views/training_levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @training_level.logo.url(:medium) %>
</p>

<p>
  <b><%= t('activerecord.attributes.training_level.name').capitalize %>:</b>
  <%= @training_level.name %>
</p>

<p>
  <b><%= t('activerecord.attributes.training_level.short_name').capitalize %>:</b>
  <%= @training_level.short_name %>
</p>

<p>
  <b><%= t('activerecord.attributes.training_level.url').capitalize %>:</b>
  <%= link_to @training_level.url, @training_level.url %>
</p>


<p>
  <b><%= t('activerecord.attributes.training_level.description').capitalize %>:</b>
  <%= @training_level.description %>
</p>

<p>
  <b><%= t('activerecord.attributes.training_level.parent').capitalize %>:</b>
  <%= @training_level.parent.name if @training_level.parent %>
</p>

<%= render "level_descriptions/level_description", :level_description => @training_level.level_description if @training_level.is_leaf? and @training_level.level_description %> 

<%= render :partial => "level_descriptions/description_levers" if @training_level.is_leaf? %>

 <%= link_to t('subjects'), subjects_path(:scope => @training_level) %> |

<%= link_to t('edit'), edit_training_level_path(@training_level) %> |
<%= link_to t('back'), training_levels_path %>