config/routes.rb
Gestor::Application.routes.draw do
  resources :evaluable_competencies

  resources :teaching_units

  resources :evaluation_criteria

  resources :learning_outcomes

  resources :subject_competencies

  resources :level_goals

  resources :qualifications

  resources :competencies

  resources :level_descriptions

  resources :subjects

  resources :training_levels
  root :to => 'training_levels#index'
end

app/models/competency.rb
class Competency < ActiveRecord::Base
  attr_accessible :level_description_id, :statement
  belongs_to :level_description
  has_many :subjects, :through => :subject_competencies

  validates_presence_of :level_description_id, :statement
end

app/controllers/competencies_controller.rb
class CompetenciesController < ApplicationController
  # GET /competencies
  # GET /competencies.json
  def index
    @competencies = Competency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @competencies }
    end
  end

  # GET /competencies/1
  # GET /competencies/1.json
  def show
    @competency = Competency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @competency }
    end
  end

  # GET /competencies/new
  # GET /competencies/new.json
  def new
    @competency = Competency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @competency }
    end
  end

  # GET /competencies/1/edit
  def edit
    @competency = Competency.find(params[:id])
  end

  # POST /competencies
  # POST /competencies.json
  def create
    @competency = Competency.new(params[:competency])

    respond_to do |format|
      if @competency.save
        format.html { redirect_to @competency, :notice => t('successfully_created', :model => t('competency.gender', :count => 1)) }
        format.json { render json: @competency, status: :created, location: @competency }
      else
        format.html { render action: "new" }
        format.json { render json: @competency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /competencies/1
  # PUT /competencies/1.json
  def update
    @competency = Competency.find(params[:id])

    respond_to do |format|
      if @competency.update_attributes(params[:competency])
        format.html { redirect_to @competency, :notice => t('successfully_updated', :model => t('competency.gender', :count => 1)) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @competency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competencies/1
  # DELETE /competencies/1.json
  def destroy
    @competency = Competency.find(params[:id])
    @competency.destroy

    respond_to do |format|
      format.html { redirect_to competencies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/competencies_helper.rb
module CompetenciesHelper
end

app/views/competencies/_competency.html.erb
 <li><%= competency.statement %></li>

app/views/competencies/_form.html.erb
<%= form_for(@competency) do |f| %>

<%= error_explanation_for @competency %>

  <div class="field">
    <%= f.label :statement %><br />
    <%= f.text_area :statement %>
  </div>
  <div class="field">
    <%= f.label :level_description_id %><br />
    <%= f.number_field :level_description_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/competencies/edit.html.erb
<h1><%= t('competency.edit') %></h1>

<%= render 'form' %>

<%= link_to t('show'), @competency %> |
<%= link_to t('back'), competencies_path %>

app/views/competencies/index.html.erb
<h1><%= t('competency.list') %></h1>

<table>
  <tr>
    <th><%= t('activerecord.attributes.competency.statement').capitalize %></th>
    <th><%= t('activerecord.attributes.competency.level_description').capitalize %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @competencies.each do |competency| %>
  <tr>
    <td><%= competency.statement %></td>
    <td><%= competency.level_description.training_level.name %></td>
    <td><%= link_to t('show'), competency %></td>
    <td><%= link_to t('edit'), edit_competency_path(competency) %></td>
    <td><%= link_to t('destroy'), competency, :confirm => t('are_you_sure'), :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('competency.new').capitalize, new_competency_path %>

app/views/competencies/new.html.erb
<h1><%= t('competency.new') -%></h1>

<%= render 'form' %>

<%= link_to t('back'), competencies_path %>

app/views/competencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t('activerecord.attributes.competency.statement').capitalize %>:</b>
  <%= @competency.statement %>
</p>

<p>
  <b><%= t('activerecord.attributes.competency.level_description').capitalize %>:</b>
  <%= @competency.level_description_id %>
</p>


<%= link_to t('edit'), edit_competency_path(@competency) %> |
<%= link_to t('back'), competencies_path %>