config/routes.rb
Gestor::Application.routes.draw do
  resources :evaluable_competencies

  resources :teaching_units

  resources :evaluation_criteria

  resources :learning_outcomes

  resources :subject_competencies

  resources :level_goals

  resources :qualifications

  resources :competencies

  resources :level_descriptions

  resources :subjects

  resources :training_levels
  root :to => 'training_levels#index'
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :code, :abbreviation, :description, :title, :training_level_id, 
                  :logo, :url, :value, :value_unit, :teaching_hours, 
		  :competency_ids, :qualification_ids, :level_goal_ids,
		  :subject_competencies_attributes,
                  :learning_outcomes

  belongs_to :training_level
  has_many :subject_competencies, :dependent => :destroy
# accepts_nested_attributes_for :subject_competencies, :allow_destroy => true
  has_many :competencies, :through => :subject_competencies
  has_many :learning_outcomes
  has_and_belongs_to_many :qualifications
  has_and_belongs_to_many :level_goals

  UNITS = [
    #disp value               #db value
    ["ECTS",                  "ects"],
    ["datetime.prompts.hour", "h"   ]
  ]


  validates :title, :training_level, :code, :presence => true
  validates :title, :code, :uniqueness => true
  validates_numericality_of :value, :teaching_hours

  validates :url, :uri => { 
     :format => /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix }

  validates_inclusion_of :value_unit, :in => UNITS.map { |disp, value| value }
  validate :terminal_level

  has_attached_file :logo, :styles => { :medium => "300x300>", 
                                        :small => "100x100>", 
                                        :tiny => "32x32>", 
                                        :invisible => "16x16>" },
                           :default_url => '/images/:attachment/missing_:style.png'

  def competency_ids=(args)
    self.subject_competencies.each { |sc| sc.destroy }
    args.each do |id|
      self.subject_competencies << SubjectCompetency.create(:competency_id => id, :subject_id => self.id)
    end
  end

  protected

  def terminal_level
    unless self.training_level
      error.add(:training_level_id, I18n.t('subject.invalid_level'))
      return false
    end
    error.add(:trainin_level_id, I18n.t('not_terminal')) unless self.training_level.is_leaf? 
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  # GET /subjects
  # GET /subjects.json
  def index
    if (params["scope"])
      @roots = [TrainingLevel.find(params["scope"])]
    else
      @roots = TrainingLevel.roots
    end
     
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subjects }
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @subject = Subject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/new
  # GET /subjects/new.json
  def new
    @subject = Subject.new
    @subject.training_level = TrainingLevel.find(params["training_level"]) if params["training_level"]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/1/edit
  def edit
    @subject = Subject.find(params[:id])
  end

  # POST /subjects
  # POST /subjects.json
  def create
    competencies = params["subject"]["competency_ids"].map{ |el| el.to_i }
    params["subject"]["competency_ids"] = []
    @subject = Subject.new(params["subject"])

    respond_to do |format|
      if @subject.save
    competencies.each do |cid|
      SubjectCompetency.create( :subject_id => @subject.id, :competency_id => cid )
    end
        format.html { redirect_to @subject, :notice => t('successfully_created', :model => t('Subject.gender', :count => 1 ) ) }
        format.json { render json: @subject, status: :created, location: @subject }
      else
        format.html { render action: "new" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subjects/1
  # PUT /subjects/1.json
  def update
    params["subject"]["competency_ids"] ||= {}
    params["subject"]["qualification_ids"] ||= {}
    params["subject"]["level_goal_ids"] ||= {}
    @subject = Subject.find(params[:id])

    respond_to do |format|
      if @subject.update_attributes(params[:subject])
        format.html { redirect_to @subject, :notice => t('successfully_updated', :model => t('Subject.gender', :count => 1 ) ) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_association_of.html.erb
<% show = [show] unless show.respond_to? :each %>

  <h3><%= t("subject.all_#{ relation.to_s.pluralize }") %></h3>
  <p>
  <% for related in subject.training_level.send(relation.to_s.pluralize) %>
    <%= check_box_tag "subject[#{relation.to_s}_ids][]", related.id, subject.send(relation.to_s.pluralize).include?(related), :id => "subject_#{ relation.to_s }_ids_#{related.id}"  %>
    <label for="<%= "subject_#{ relation.to_s }_ids_#{related.id}" -%>">
    <% show.each do |field| %>
      <% if field.is_a? Symbol %>
        <%= related.send(field) %>
      <% else %>
        <%= field %>
      <% end %>
    <% end %>
    </label>
    <%#= competency_link_to t("competency.work_on_this"), related, subject, relation  %>
    <br/>
      <% end %>

app/views/subjects/_form.html.erb
<%= form_for(@subject, :html => { :multipart => true }) do |f| %>

<%= error_explanation_for @subject %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :abbreviation %><br />
    <%= f.text_field :abbreviation %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.number_field :value %>
    <%= f.select :value_unit, translate_options_for(Subject::UNITS) %>
  </div>
  <div class="field">
    <%= f.label :teaching_hours %><br />
    <%= f.number_field :teaching_hours %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.file_field :logo %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url%>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :training_level_id %><br />
    <%= f.collection_select :training_level_id, TrainingLevel.modules(), :id, :name %>
  </div>

  <%= render 'association_of', :subject => f.object, :relation => :level_goal , :show => :statement %>
  <%= render 'association_of', :subject => f.object, :relation => :competency , 
                                                     :show => :statement %>
  <%= render 'association_of', :subject => f.object, :relation => :qualification, :show => ['(', :code, ')',  :statement]  %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/subjects/_show_associations_of.html.erb
<h2><%= t("subject.#{association.to_s.pluralize}") -%></h2>

<% if subject.send(association.to_s.pluralize).blank?  %>
  <p><%= t("subject.still_no_#{association.to_s.pluralize}") %>.</p>
<% else %>
  <ul><%= render subject.send(association.to_s.pluralize), :subject => subject %></ul>
<% end %>

app/views/subjects/_subject_index.html.erb
  <tr>
    <td><%= conditional_link(subject, image_tag(subject.logo.url(:tiny))) %></td>
    <td align="right"><%= "#{subject.value} #{translate_option_for Subject::UNITS, subject.value_unit}" %></td>
    <td align="center"><%= "#{subject.teaching_hours} h." %></td>
    <td><%= conditional_link(subject, subject.title) %>
        <%= "(#{ subject.abbreviation })" unless subject.abbreviation.blank? -%>
    </td>
    <td><%= link_to t('show'), subject %></td>
    <td><%= link_to t('edit'), edit_subject_path(subject) %></td>
    <td><%= link_to t('destroy'), subject, :confirm => t('are_you_sure'), :method => :delete %></td>
  </tr>

app/views/subjects/_subjects_index.html.erb
<table>
  <tr>
    <th></th>
    <th><%= t('activerecord.attributes.subject.value').capitalize %></th>
    <th><%= t('activerecord.attributes.subject.teaching_hours').capitalize %></th>
    <th><%= t('activerecord.attributes.subject.title').capitalize %> </th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% subjects.each do |subject| %>
  <%= render 'subject_index', :subject => subject %>
<% end %>
</table>

app/views/subjects/_training_sublevel.html.erb
  <div class="Nested">
    <p style="font-size: <%= 16 - 2 * depth -%>pt;"><b><%= link_to unit.name, subjects_path(:scope => unit) %></b></p>
    <% if unit.is_leaf? %>
      <%= render 'subjects_index', :subjects => unit.subjects %>

       <br />
       <%= link_to t('subject.new').capitalize, new_subject_path(:training_level => unit) %>
       <p>&nbsp</p>
    <% end %>

    <% unit.children.each do |child| %>
      <%= render 'training_sublevel', :unit => child, :depth => (depth + 1) %>
    <% end %>

  </div>

app/views/subjects/edit.html.erb
<h1><%= t('subject.edit') %></h1>

<%= render 'form' %>

<%= link_to t('show'), @subject %> |
<%= link_to t('back'), subjects_path %>

app/views/subjects/index.html.erb
<h1><%= link_to t('subject.list'), subjects_path %></h1>

<% @roots.each do |unit| %>
  <%= render 'training_sublevel', :unit => unit, :depth => 0 %>
  <% end %>

  <p> <%= link_to t('subject.new').capitalize, new_subject_path %> </p>

app/views/subjects/new.html.erb
<h1><%= t('subject.new') -%></h1>

<%= render 'form' %>

<%= link_to t('back'), subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p style="position: relative; left: -50px;">
</p>

<div style="">
  
  <h1 style="text-align: center;"><%= image_tag @subject.logo.url(:small), :style => "float:left;" %> <%= @subject.title %></h1>
   
   <div style="text-align: center;">
   <em>
     <%= t('activerecord.attributes.subject.code').capitalize %> <%= @subject.code %>
     -
     <%= @subject.value %> <%= translate_option_for Subject::UNITS, @subject.value_unit %>
     -
     <%= @subject.teaching_hours %> 
     <%= t('activerecord.attributes.subject.teaching_hours').capitalize %>
     </em>
     <%= @subject.training_level.name %><br/>
     <%= link_to @subject.url, @subject.url unless @subject.url.blank? %><br/>
   </div>
   
   
   <p>
     <%= RedCloth.new(sanitize(@subject.description), [:filter_html, :filter_styles, :filter_classes, :filter_ids]).to_html.html_safe %>
   </p>
   

<%= render 'show_associations_of', :subject => @subject, :association => :level_goal %>
<%= render 'show_associations_of', :subject => @subject, :association => :competency %>
<%= render 'show_associations_of', :subject => @subject, :association => :qualification %>

<%= link_to t('learning_outcomes'), learning_outcomes_path(:subject => @subject) %> |
<%= link_to t('edit'), edit_subject_path(@subject) %> |
<%= link_to t('back'), subjects_path(:scope => @subject.training_level) %>

</div>