config/routes.rb
Gestor::Application.routes.draw do
  resources :evaluable_competencies

  resources :teaching_units

  resources :evaluation_criteria

  resources :learning_outcomes

  resources :subject_competencies

  resources :level_goals

  resources :qualifications

  resources :competencies

  resources :level_descriptions

  resources :subjects

  resources :training_levels
  root :to => 'training_levels#index'
end

app/models/level_description.rb
class LevelDescription < ActiveRecord::Base
  attr_accessible :training_level_id, 
                  :competencies_attributes, 
                  :qualifications_attributes, 
                  :level_goals_attributes,
                  :main_competency,
                  :european_benchmark,
                  :professional_profile,
                  :professional_environment,
                  :relevant_jobs,
                  :professional_family,
                  :prospective_of_the_degree

  belongs_to :training_level
  has_many :competencies, :dependent => :destroy
  accepts_nested_attributes_for :competencies, :allow_destroy => true
  has_many :qualifications, :dependent => :destroy
  accepts_nested_attributes_for :qualifications, :allow_destroy => true
  has_many :level_goals, :dependent => :destroy
  accepts_nested_attributes_for :level_goals, :allow_destroy => true


  validates :training_level_id, :presence => true, :uniqueness => true
  validate :valid_training_level
  validate :assign_to_terminal_level, :if => Proc.new {|a| a.training_level }

  def valid_training_level
    errors.add(:training_level_id, I18n.t('activerecord.errors.messages.record_invalid')) unless training_level
  end

  def assign_to_terminal_level
    errors.add(:training_level_id, I18n.t('not_terminal')) unless training_level.is_leaf?
  end

end

app/controllers/level_descriptions_controller.rb
class LevelDescriptionsController < ApplicationController
  # GET /level_descriptions
  # GET /level_descriptions.json
  def index
    @level_descriptions = LevelDescription.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @level_descriptions }
    end
  end

  # GET /level_descriptions/1
  # GET /level_descriptions/1.json
  def show
    @level_description = LevelDescription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @level_description }
    end
  end

  # GET /level_descriptions/new
  # GET /level_descriptions/new.json
  def new
    @level_description = LevelDescription.new
    @level_description.training_level = TrainingLevel.find(params["training_level"])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @level_description }
    end
  end

  # GET /level_descriptions/1/edit
  def edit
    @level_description = LevelDescription.find(params[:id])
  end

  # POST /level_descriptions
  # POST /level_descriptions.json
  def create
    @level_description = LevelDescription.new(params[:level_description])

    respond_to do |format|
      if @level_description.save
        format.html { redirect_to @level_description, :notice => t('successfully_created', :model => t('LevelDescription.gender', :count => 1)) }
        format.json { render json: @level_description, status: :created, location: @level_description }
      else
        format.html { render action: "new" }
        format.json { render json: @level_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /level_descriptions/1
  # PUT /level_descriptions/1.json
  def update
    @level_description = LevelDescription.find(params[:id])

    respond_to do |format|
      if @level_description.update_attributes(params[:level_description])
        format.html { redirect_to @level_description, :notice  => t('successfully_updated', :model => t("level_description.gender", :count => 1)) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @level_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /level_descriptions/1
  # DELETE /level_descriptions/1.json
  def destroy
    @level_description = LevelDescription.find(params[:id])
    @level_description.destroy

    respond_to do |format|
      format.html { redirect_to level_descriptions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/level_descriptions_helper.rb
module LevelDescriptionsHelper
end

app/views/level_descriptions/_competency_fields.html.erb
<%= f.text_area :statement, :rows => 4, :cols => 80 %>
<%= f.link_to_remove t("competency.remove") %><br />

app/views/level_descriptions/_description_levers.html.erb
<% if @training_level.level_description %>
<%= link_to t('level_description.edit').capitalize, edit_level_description_path(@training_level.level_description, :training_level => @training_level) %>
<% else %>
<%= link_to t('level_description.new').capitalize, new_level_description_path(:training_level => @training_level) %>
<% end %>
|

app/views/level_descriptions/_form.html.erb
<%= nested_form_for(@level_description) do |f| %>

<%= error_explanation_for @level_description %>

    <%= f.hidden_field :training_level_id %>

  <div class="field">
    <%= f.label :european_benchmark %><br />
    <%= f.text_area :european_benchmark, :rows => 1 %>
  </div>

  <div class="field">
    <%= f.label :professional_family %><br />
    <%= f.text_field :professional_family, :cols => 60  %>
  </div>


    <h3><%= t('level_goals') %></h3>
    <%= f.fields_for  :level_goals %>
    <p><%= f.link_to_add t("level_goal.new"), :level_goals %></p>

  <div class="field">
    <%= f.label :main_competency %><br />
    <%= f.text_area :main_competency, :rows => 8, :cols => 80 %>
  </div>

    <h3><%= t('competencies') %></h3>
    <%= f.fields_for  :competencies %>
    <p><%= f.link_to_add t("competency.new"), :competencies %></p>

    <h3><%= t('qualifications') %></h3>
    <%= f.fields_for  :qualifications %>
    <p><%= f.link_to_add t("qualification.new"), :qualifications %></p>


  <div class="field">
    <%= f.label :professional_profile %><br />
    <%= f.text_area :professional_profile, :rows => 4, :cols => 80 %>
  </div>

  <div class="field">
    <%= f.label :professional_environment %><br />
    <%= f.text_area :professional_environment, :rows => 4, :cols => 80 %>
  </div>

  <div class="field">
    <%= f.label :relevant_jobs%><br />
    <%= f.text_area :relevant_jobs, :rows => 4, :cols => 80 %>
  </div>

  <div class="field">
    <%= f.label :prospective_of_the_degree %><br />
    <%= f.text_area :prospective_of_the_degree, :rows => 4, :cols => 80 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/level_descriptions/_level_description.html.erb
<%= show_fields %w{professional_family main_competency european_benchmark professional_profile professional_environment relevant_jobs prospective_of_the_degree }, level_description %>

  <h2><%= t('activerecord.attributes.level_description.training_level').capitalize %>:
  <%= level_description.training_level.name %></h2>

  <h3><%= t('level_goals') -%></h3>

  <%= t('level_goal.empty') if level_description.level_goals.empty? %>
  <ol class="Alpha"> <%= render level_description.level_goals %></Ol>

  <h3><%= t('competencies') -%></h3>

  <%= t('competency.empty') if level_description.competencies.empty? %>
  <ol class="Alpha"> <%= render level_description.competencies %></ol>

  <h3><%= t('qualifications') -%></h3>

  <%= t('qualification.empty') if level_description.qualifications.empty? %>
  <ul> <%= render level_description.qualifications %></ul>

app/views/level_descriptions/_level_goal_fields.html.erb
<%= f.text_area :statement, :cols => 80, :rows => 4 %>
<%= f.link_to_remove t("level_goal.remove") %><br />

app/views/level_descriptions/_qualification_fields.html.erb
<table>
  <tr>
    <th><%= f.label :code %></th>
    <td><%= f.text_field :code, :cols => 7 %></td>
    -
    <th><%= f.check_box :partial %>
    <%= f.label :partial %></th>
  </tr>
  <tr>
    <th><%= f.label :statement %></th>
    <td><%= f.text_area :statement, :rows => 2, :cols => 50 %></td>
    <td><%= f.link_to_remove t("qualification.remove") %></td>
  <tr/>
</table>

app/views/level_descriptions/edit.html.erb
<h1><%= t('level_description.edit') %> </h1>
<h2><%= @level_description.training_level.name %></h2>

<%= render 'form' %>

<%= link_to t('show'), @level_description %> |
<%= link_to t('back'), training_levels_path %>

app/views/level_descriptions/index.html.erb
<h1><%= t('level_description.list') %></h1>

<table>
  <tr>
    <th><%= t('activerecord.attributes.level_description.training_level').capitalize %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @level_descriptions.each do |level_description| %>
  <tr>
    <td><%= level_description.training_level_id %></td>
    <td><%= link_to t('show'), level_description %></td>
    <td><%= link_to t('edit'), edit_level_description_path(level_description) %></td>
    <td><%= link_to t('destroy'), level_description, :confirm => t('are_you_sure'), :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/level_descriptions/new.html.erb
<h1><%= t('level_description.new') -%></h1>

<%= render 'form' %>

<%= link_to t('back'), training_levels_path %>

app/views/level_descriptions/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @level_description.training_level.name %></h1>

<%= render 'level_description', :level_description => @level_description %>

<%= link_to t('edit'), edit_level_description_path(@level_description, :training_level => @level_description.training_level) %> |
<%= link_to t('back'), training_levels_path %>